server:
  port: 8600
  servlet:
    context-path: /vuelos
eureka:
  client:
    service-url:
      defaultZone: http://10.2.4.12:8761/eureka
  instance:
    ip-address:  10.2.4.12
    prefer-ip-adress: true
    instance-id: 10.2.4.12:8600
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/viajes
spring:
  datasource:
    username: root
spring:
  datasource:
    password: root
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
